# Generated by Django 5.2.7 on 2025-10-31 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blooddonation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logindoner',
            old_name='Password',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='logindoner',
            old_name='address',
            new_name='last_name',
        ),
        migrations.RemoveField(
            model_name='logindoner',
            name='bloodtype',
        ),
        migrations.AddField(
            model_name='logindoner',
            name='blood_type',
            field=models.CharField(default='O+', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='logindoner',
            name='email',
            field=models.EmailField(default='testmain@123.com', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='logindoner',
            name='is_donor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='logindoner',
            name='password',
            field=models.CharField(default='ChangeME123', max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='logindoner',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
